<a href="https://colab.research.google.com/github/gyanaa/Tensorflow-primer-1.0/blob/master/Tensorflow_Primer_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
import numpy as np


In [23]:
a = tf.constant ([1,2,3])
b = tf.constant ([1,2,3])
print (a)
print (b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [24]:
a = tf.constant ([1,2,3])
b = tf.constant ([1,2,3])
c = tf.add (a,b)
print (a)
print (b)
print (c)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [25]:
a = tf.constant ([1.0,2,3])
b = tf.constant ([1,2.0,3])
c = tf.add (a,b)
print (a)
print (b)
print (c)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)


In [26]:
a = tf.constant ([1,2,3])
b = tf.constant ([1,2,3])
c = tf.add (a,b)
print (a)
print (b)
print (c)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [0]:
with tf.sessio

In [20]:
with ts.session() as sess:

SyntaxError: ignored

In [17]:
ts.

SyntaxError: ignored