<a href="https://colab.research.google.com/github/gyanaa/Tensorflow-primer-1.0/blob/master/Tensorflow_Primer_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as ts

In [0]:
import numpy as np


In [5]:
a = ts.constant ([1,2,3])
b = ts.constant ([1,2,3])
print (a)
print (b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [6]:
a = ts.constant ([1,2,3])
b = ts.constant ([1,2,3])
c = ts.add (a,b)
print (a)
print (b)
print (c)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [8]:
a = ts.constant ([1.0,2,3])
b = ts.constant ([1,2.0,3])
c = ts.add (a,b)
print (a)
print (b)
print (c)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)


In [0]:
a = ts.constant ([1,2,3])
b = ts.constant ([1,2,3])
c = ts.add (a,b)
print (a)
print (b)
print (c)

In [17]:
ts.

SyntaxError: ignored